default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: carloss

development:
  <<: *default
  database: Recipe_App_Rails_development
  

test:
  <<: *default
  database: Recipe_App_Rails_test
  

production:
  <<: *default
  database: Recipe_App_Rails_production
  username: postgres
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
